import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as M from '../src/core.js';
function intake(c){M.stageInput(c,c.intake);M.extract(c);for(const i of c.batch)M.review(c,i,'accept');M.confirmBatch(c);}
function prep(c){M.advance(c);M.advance(c);M.confirmPlan(c,{goal:'核实维护影响'});}
function visit(c){M.endRoleplay(c,true);M.recordVisit(c,M.demoVisit);M.extract(c);for(const i of c.batch)M.review(c,i,'accept');M.confirmBatch(c);M.advance(c);M.advance(c);for(const a of c.actions.filter(a=>a.round===c.version+1))M.reviewAction(c,a.id,'accept');M.confirmActions(c);M.saveVersion(c);}
test('complete demo V1 -> V2 -> V3, immutable snapshots and stable IDs',()=>{const c=M.demoCustomer();intake(c);const v1=JSON.stringify(c.versions[0]);prep(c);visit(c);assert.equal(c.version,2);assert.equal(c.opportunityStage.stage,2);assert.equal(JSON.stringify(c.versions[0]),v1);M.nextRound(c);prep(c);visit(c);assert.equal(c.version,3);assert.equal(new Set(c.information.map(i=>i.id)).size,c.information.length);M.validate(c);});
test('pending information and actions block progression and save',()=>{const c=M.demoCustomer();M.stageInput(c,c.intake);M.extract(c);assert.throws(()=>M.confirmBatch(c));assert.throws(()=>M.saveVersion(c));assert.throws(()=>M.advance(c));});
test('roleplay is isolated and unknown actor statements are never imported',()=>{const c=M.demoCustomer();intake(c);prep(c);const count=c.information.length;M.startRoleplay(c,'采购','谨慎简短');M.chat(c,'预算多少，一定会买吗？');assert.equal(c.information.length,count);assert.equal(c.roleplays.at(-1).context.scenarioFacts.budget.status,'UNKNOWN');assert.equal(c.roleplays.at(-1).context.scenarioFacts.budget.value,null);M.endRoleplay(c);assert.equal(c.sources.some(s=>s.origin==='ROLEPLAY'),false);});
test('acceptance never upgrades customer statement to FACT',()=>{const c=M.demoCustomer();M.stageInput(c,c.intake);M.extract(c);const i=c.information.find(i=>i.type==='CUSTOMER_STATED');M.review(c,i.id,'accept');assert.equal(i.type,'CUSTOMER_STATED');assert.throws(()=>M.review(c,i.id,'edit',{content:'设备已老化',type:'FACT'}));});
test('correction logs before/after and does not overwrite V1',()=>{const c=M.demoCustomer();intake(c);const prior=JSON.stringify(c.versions[0]);M.correct(c,'I01');M.review(c,'I01','edit',{content:'机构级别未知',type:'UNVERIFIED'});assert.throws(()=>M.confirmBatch(c));M.review(c,'I01','accept');M.confirmBatch(c);assert.equal(JSON.stringify(c.versions[0]),prior);assert.ok(c.changeLog.some(l=>l.kind==='信息审核'));assert.equal(c.state,'CUSTOMER_ANALYSIS');});
test('real customer refuses simulated visit; fields remain unknown',()=>{const c=M.createCustomer({name:'机构B',customerId:'R1',caseType:'REAL_DEIDENTIFIED',intake:{statements:'情况未知'}});intake(c);prep(c);M.endRoleplay(c,true);assert.throws(()=>M.recordVisit(c,M.demoVisit));assert.ok(c.information.every(i=>i.type!=='FACT'));});
test('edited actions require second acceptance',()=>{const c=M.demoCustomer();intake(c);prep(c);M.endRoleplay(c,true);M.recordVisit(c,M.demoVisit);M.extract(c);c.batch.forEach(i=>M.review(c,i,'accept'));M.confirmBatch(c);M.advance(c);M.advance(c);const a=c.actions[0];M.reviewAction(c,a.id,'edit',{title:'核实实际影响'});assert.throws(()=>M.confirmActions(c));});
test('manual opportunity review cannot invent unsupported stages',()=>{const c=M.demoCustomer();intake(c);prep(c);M.endRoleplay(c,true);M.recordVisit(c,M.demoVisit);M.extract(c);c.batch.forEach(i=>M.review(c,i,'accept'));M.confirmBatch(c);M.advance(c);assert.throws(()=>M.manualAssessment(c,M.clone(c.assessment),3,'客户友好','未知','未结局'));const rows=M.clone(c.assessment);M.manualAssessment(c,rows,2,'已明确维护协调诉求','尚无采购项目范围','未结局');assert.equal(c.opportunityStage.mode,'HUMAN_REVIEW');assert.throws(()=>M.manualAssessment(c,rows,6,'没回消息','不适用','失单'));});
test('invalid edit is atomic and conflict excludes both sides',()=>{const c=M.demoCustomer();M.stageInput(c,c.intake);M.extract(c);const before=M.clone(c.information[0]);assert.throws(()=>M.review(c,'I01','edit',{content:'bad',type:'UNVERIFIED',replaces:['I999']}));assert.deepEqual(c.information[0],before);c.batch.forEach(i=>M.review(c,i,'accept'));M.review(c,'I04','edit',{content:c.information.find(i=>i.id==='I04').content,type:'CUSTOMER_STATED',conflicts:['I05']});M.review(c,'I04','accept');M.confirmBatch(c);assert.ok(!M.active(c).some(i=>['I04','I05'].includes(i.id)));});
