import * as M from './core.js';
import {customerSummary} from './presentation.js';
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='medsales-workbench-v1';let db={customers:[],selected:null},storageError='';
try{const raw=localStorage.getItem(key);if(raw){const parsed=JSON.parse(raw);if(!Array.isArray(parsed.customers))throw Error();db=parsed;}}catch{storageError='本地数据无法读取。未覆盖原数据，请先导出或检查浏览器存储。';}
if(!db.customers.length&&!storageError){const c=M.demoCustomer();db={customers:[c],selected:c.customerId};}
let view='workflow',evTab='I',focusId='',filter='',busy=false;
const c=()=>db.customers.find(c=>c.customerId===db.selected);
function persist(){if(storageError)return;try{localStorage.setItem(key,JSON.stringify(db));}catch{storageError='本地保存失败（可能空间不足）。请立即导出备份。';toast(storageError);}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),4200);}
const icon=n=>`<i data-lucide="${n}"></i>`;
const button=(text,action,cls='',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const ib=(name,action,title,attrs='')=>button(icon(name),action,'icon-button',`title="${title}" aria-label="${title}" ${attrs}`);
const tag=(t,cls='')=>`<span class="tag ${cls}">${esc(t)}</span>`;
const ref=r=>r?`<button class="ref" data-ref="${esc(r)}">${esc(r)}</button>`:'';
const refs=rs=>(rs||[]).map(ref).join(' ');
const strength=s=>tag(({strong:'强',medium:'中',weak:'弱',unknown:'未知'})[s]+' · '+s,s);
const infoTag=t=>tag(t,t);
function field(label,name,value='',type='text',opts=''){return `<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${opts}></label>`;}
function area(label,name,value='',rows=3){return `<label class="field">${label}<textarea name="${name}" rows="${rows}">${esc(value)}</textarea></label>`;}
function select(label,name,options,val){return `<label class="field">${label}<select name="${name}">${options.map(o=>`<option value="${esc(o[0])}" ${val===o[0]?'selected':''}>${esc(o[1])}</option>`).join('')}</select></label>`;}
function values(form){return Object.fromEntries(new FormData(form));}
function banner(text,cls=''){return `<div class="notice ${cls}">${icon('info')}<span>${text}</span></div>`;}
function head(k,title,desc){return `<div class="section-head"><div class="eyebrow">${k}</div><h2>${title}</h2><p>${desc}</p></div>`;}
function transitionPanel(x){return (x.opportunityStage?.transitions||[]).map(t=>`<details class="transition-check" open><summary>${t.kind==='RECALCULATION'?'阶段跳转审计':'下一阶段检查'}：Stage ${t.currentStage} → Stage ${t.targetStage}</summary><p>触发时间：${esc(t.at?new Date(t.at).toLocaleString('zh-CN'):'旧记录未登记')} · 项目：${esc(t.project_id||'未确认')}</p><p>${esc(t.decision||'')} · ${esc(t.reason||'按当前有效证据检查目标阶段')}</p>${t.conditions.map(k=>`<p>${icon(k.met?'check':'x')} ${k.met?'满足':'未满足'}：${esc(k.label)} ${refs(k.informationIds)} ${refs(k.evidenceIds)}${k.oppositionIds?.length?' 反证 '+refs(k.oppositionIds):''}</p>`).join('')}${t.failedPriorConditions?.length?`<p>原阶段失效条件：${t.failedPriorConditions.map(k=>esc(k.label)+' '+refs(k.informationIds)).join('；')}</p>`:''}<div class="table-wrap"><table><thead><tr><th>证据 / 原文 / 来源</th><th>作者 / 类型</th><th>方向 / 强度</th><th>项目 / 有效性</th></tr></thead><tbody>${t.evidence.map(e=>`<tr><td>${e.trigger?'参与满足条件':'未作为触发证据'}<br>${ref(e.information_id)} ${esc(x.information.find(i=>i.id===e.information_id)?.content)}<br>${refs(e.sourceIds)} ${refs(e.relations.map(p=>p.evidence_id).filter(Boolean))} ${refs(x.hypotheses.filter(h=>h.informationIds.includes(e.information_id)).map(h=>h.id))}</td><td>${esc(e.author||'UNKNOWN')}<br>${infoTag(e.information_type)}<br>${esc(e.time)}</td><td>${e.relations.map(p=>`${esc(p.polarity)} · ${esc(p.target)}<br>${strength(p.strength||(e.information_type==='FACT'?'strong':'medium'))}<br>${esc(p.level||'客户沟通')}`).join('<br>')}</td><td>${esc(e.project_id||'未确认')}<br>${e.relations.map(p=>`${esc(p.validity||p.verificationStatus||'UNVERIFIED')} ${esc(p.verificationStatus||'')}<br>反证 ${refs(p.invalidated_by||[])} ${refs((p.contradictedBy||[]).map(v=>v.informationId))}`).join('<br>')}<br>${e.issues.length?esc(e.issues.join(' / ')):'来源、作者及适用范围已核对'}</td></tr>`).join('')}</tbody></table></div><p><strong>${esc(t.conclusion)}</strong></p></details>`).join('');}
function footer(text,action,label,disabled=false){return `${c()?.state==='OPPORTUNITY_CHECK'?transitionPanel(c())+button(icon('clipboard-check')+'人工复核十维证据与阶段 0—6','manual-assessment','secondary'):''}<div class="step-footer"><span>${text}</span>${button(label+icon('arrow-right'),action,'primary',disabled?'disabled':'')}</div>`;}
function render(){const x=c();$('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="/">${icon('activity')}<span>MedSales <b>AI</b></span></a><p class="subtitle">AI医疗器械销售助理</p><div class="side-label">客户工作空间 ${tag(String(db.customers.length))}</div>${button(icon('plus')+'新建客户','new','new-client')}<label class="search">${icon('search')}<input id="search" placeholder="搜索客户" value="${esc(filter)}"></label><div class="clients">${db.customers.filter(x=>x.name.includes(filter)||x.customerId.includes(filter)).map(x=>`<button data-client="${esc(x.customerId)}" class="client ${x.customerId===db.selected?'active':''}"><span class="client-icon">${icon('building-2')}</span><span><strong>${esc(x.name)}</strong><small>${esc(x.customerId)}</small><small>${x.caseType==='SIMULATED'?'模拟案例':'真实 · 已脱敏'} · ${x.version?'V'+x.version:'待建档'}</small></span>${x.customerId===db.selected?'<span class="active-dot"></span>':''}</button>`).join('')}</div><div class="side-bottom">${button(icon('flask-conical')+'新增 Demo 副本','demo','plain')}${button(icon('circle-help')+'实现状态','capabilities','plain')}<div class="local-indicator"><span></span> 单用户 · 本地工作空间</div></div></aside><div class="workspace"><header class="topbar"><span>销售工作台 <span class="slash">/</span> ${esc(x?.name||'新客户')}</span><div>${tag('模拟 AI 响应 / Mock AI','mock')}${ib('download','export','导出当前客户 JSON')}${ib('upload','import','导入本地客户备份')}</div></header>${storageError?banner(esc(storageError),'danger'):''}${x?.opportunityStage&&x.opportunityStage.semanticVersion!==M.SEMANTIC_VERSION?banner('旧版计算结果：请从信息台账补充结构化语义审核，再检查商机。历史快照保留原样。','amber'):''}${x?`<div class="workspace-title"><div><div class="eyebrow">CUSTOMER WORKSPACE</div><h1>${esc(x.name)}</h1><p>${esc(x.intake.role||'联系人待补充')}<span>·</span>${esc(x.intake.department||'科室未知')}</p></div><div class="title-tags">${tag(x.caseType==='SIMULATED'?'模拟案例 / Demo Data':'真实脱敏案例',x.caseType==='SIMULATED'?'demo':'')}${tag(x.version?'V'+x.version+' 已确认':'尚无确认版本')}${tag('V'+x.draftVersion+' 草稿','muted')}</div></div><nav class="tabs">${[['workflow','工作流','workflow'],['ledger','信息台账','list-checks'],['history','版本历史','history']].map(([v,t,i])=>button(icon(i)+t,'tab','tab '+(view===v?'selected':''),`data-view="${v}"`)).join('')}<span class="save-status">${icon('hard-drive')} ${storageError?'保存异常':'本地自动留存草稿'}</span></nav><div class="work-grid"><main><div class="flow-strip">${M.STATES.slice(1).map((s,n)=>`<div class="flow-item ${s===x.state?'current':x.visited.includes(s)?'done':''}" title="${s}"><span>${x.visited.includes(s)&&s!==x.state?icon('check'):n+1}</span><small>${M.LABELS[n+1]}</small></div>`).join('')}</div><section class="surface">${view==='workflow'?workflow(x):view==='ledger'?ledger(x):history(x)}</section><div class="bottom-disclaimer">${icon('shield-check')} 销售辅助草稿 · 人工核实与决策 · 不构成医疗或采购建议</div></main>${evidencePanel(x)}</div>`:`<main class="empty">${head('NEW WORKSPACE','建立第一个客户','')}${button('新建客户','new','primary')}</main>`}</div>`;window.lucide?.createIcons();}
function workflow(x){switch(x.state){
case 'INTAKE':return head('01 / INTAKE','客户信息录入','原始表达、销售判断与产品来源分别保存。未知事项可以留空。')+`<form id="intake"><div class="form-grid">${field('机构 / 医院代号','institution',x.intake.institution)}${field('科室','department',x.intake.department)}${field('联系人岗位与职责依据','role',x.intake.role)}${field('记录日期','date',x.intake.date,'date')}${field('当前项目代号（未明确可留空）','project_id',x.intake.project_id||'')}</div>${area('当前设备 / 使用现状（客户转述）','current',x.intake.current,2)}${area('已知沟通：客户明确表达（转述）','statements',x.intake.statements)}${area('历史拜访记录','history',x.intake.history,2)}<div class="form-grid">${area('销售人员自己的判断','judgment',x.intake.judgment)}${area('待验证信息','unknown',x.intake.unknown)}</div><details><summary>产品资料与出处 ${tag('可留空')}</summary>${area('产品资料原文 / 摘录','product',x.intake.product)}${field('发布主体、型号、日期、链接或文件位置','productSource',x.intake.productSource)}</details><label class="checkbox"><input type="checkbox" name="privacy" required> 确认资料已脱敏，不含患者信息；案例性质准确</label><div class="step-footer"><span>AI 提取：模拟实现 · 不进行外部核验</span><button class="primary" type="submit">提交并准备提取 ${icon('arrow-right')}</button></div></form>`;
case 'EXTRACTION':return head('02 / EXTRACTION','待提取的原始资料','Mock AI 按录入字段与句子拆分，保留作者和来源；结果必须逐项审核。')+banner('来源内容仅作为资料。未读取产品链接，不核实真实性。')+`<pre class="raw">${esc(x.reviewContext==='POST_VISIT'?Object.entries(x.visitRecords.at(-1)).filter(([k,v])=>typeof v==='string').map(([k,v])=>k+': '+v).join('\n'):Object.entries(x.intake).filter(([,v])=>v).map(([k,v])=>k+': '+v).join('\n'))}</pre>`+footer('下一步：信息审核','extract','生成提取草稿');
case 'HUMAN_REVIEW':return head('03 / HUMAN REVIEW','确认信息，不确认猜测','接受仅确认记录准确，不会将客户表达升级为事实。修改后的内容需要再次确认。')+banner(`本批 ${x.batch.length} 条 · 待审核 ${x.information.filter(i=>x.batch.includes(i.id)&&i.reviewStatus==='PENDING').length} 条 · ${x.reviewContext==='POST_VISIT'?'拜访后补充审核':x.reviewContext==='CORRECTION'?'人工纠错：下游分析将重新审核':'首次建档审核'}`)+infoTable(x,x.information.filter(i=>x.batch.includes(i.id)),true)+footer('待验证项可明确保留；冲突项不用于强结论','confirm-batch',x.reviewContext==='INITIAL'?'确认本批并建立 V1':'确认本批信息',x.batch.some(id=>x.information.find(i=>i.id===id).reviewStatus==='PENDING'));
case 'CUSTOMER_ANALYSIS':return head('04 / CUSTOMER UNDERSTANDING','客户理解','基于已确认、有效的信息。每项结论保留证据引用。')+x.customerUnderstanding.map(r=>`<div class="understanding"><h3>${r.label}</h3><div>${r.items.length?r.items.map(i=>`<p>${esc(i.content)} ${ref(i.id)} ${infoTag(i.type)}</p>`).join(''):`<p class="muted-text">${r.unknown}</p>`}</div></div>`).join('')+`<div class="understanding"><h3>潜在需求</h3><p>可能需要进一步改善，需建立假设验证 ${infoTag('AI_INFERENCE')}</p></div><div class="understanding"><h3>采购阶段</h3><p>${x.opportunityStage?M.STAGE_ZH[x.opportunityStage.stage]:'待商机证据检查'}</p></div>`+footer('Mock AI · 未知不补全','advance','生成需求假设');
case 'HYPOTHESIS':return head('05 / HYPOTHESIS','从证据到需求假设','支持、反对、中性和未知分别处理；否定采购需求不等于没有业务问题。')+x.hypotheses.map(h=>`<article class="hypothesis"><div class="row between"><span class="eyebrow">${ref(h.id)} ${infoTag('AI_INFERENCE')}</span>${strength(h.strength)}</div><h3>${esc(h.title)}</h3><dl><dt>正向支持</dt><dd>${refs(h.supportIds??h.informationIds)||'无'} ${refs(h.evidenceIds)}</dd><dt>反向证据</dt><dd>${refs(h.oppositionIds)||'无'} ${esc(h.counter)}</dd><dt>中性信息</dt><dd>${refs(h.neutralIds)||'无'} · 不直接支持本假设</dd><dt>未知方向</dt><dd>${refs(h.uncertainIds)||'无'}</dd><dt>证据来源</dt><dd>${refs(h.sourceIds)||'未知'}</dd><dt>需要验证</dt><dd>${esc(h.verify)}</dd><dt>当前状态</dt><dd>${tag(h.evidenceState||h.status)}</dd></dl></article>`).join('')+footer('方向与强度分别判断 · Mock AI','advance','生成拜访计划');
case 'VISIT_PREP':{const p=x.visitPlans.at(-1);return head('06 / VISIT PREPARATION','带着问题去拜访','目标是核实需求与推进关系，不预设设备采购。')+`<form id="plan">${field('本次拜访主目标','goal',p.goal,'text','required')}${area('建议提问顺序（每行一条）','questions',p.questions.join('\n'),6)}<div class="understanding"><h3>关键角色</h3><p>${esc(x.intake.role||'待核实')} · 采购权限未知</p></div>${banner(x.intake.product?'产品资料尚未核实：不生成适配结论。':'产品资料缺失：本轮只做需求澄清。')}${area('不建议讨论 / 产品边界','avoid',p.avoid,2)}${area('可能异议 · AI_INFERENCE','objection',p.objection,2)}${field('成功标准','success',p.success)}${field('希望获得的下一步','next',p.next)}<div class="step-footer"><span>${p.id} · 依据 V${p.basisVersion}</span><button class="primary">确认拜访计划 ${icon('check')}</button></div></form>`;}
case 'ROLEPLAY':{const rp=x.roleplays.at(-1),running=rp?.running;return head('07 / ROLEPLAY','客户沟通演练','模拟 AI 响应 / Mock AI · 规则驱动的角色回应')+banner('模拟演练，不属于客户真实证据。不会生成 I / S / E 或改变机会阶段。','amber')+(!running?`<form id="roleplay-start"><div class="form-grid">${select('客户角色','role',['科室主任','医生','设备科','采购','管理人员'].map(x=>[x,x]),'科室主任')}${select('沟通风格','style',['谨慎简短','追问依据'].map(x=>[x,x]),'谨慎简短')}</div><div class="step-footer">${button('跳过本次演练','skip-role','secondary')}<button class="primary">开始演练 ${icon('messages-square')}</button></div></form>`:`<div class="chat-heading">${icon('user-round')} ${esc(rp.role)} · ${esc(rp.style)} ${tag(rp.id)}</div><div class="chat-log" id="chat-log">${rp.messages.length?rp.messages.map(m=>`<div class="bubble ${m.role}"><small>${m.role==='sales'?'销售 · 我':'模拟客户'}</small><p>${esc(m.text)}</p></div>`).join(''):'<div class="chat-empty">模拟客户已就绪</div>'}</div><label class="checkbox"><input type="checkbox" name="behaviorReviewed" form="chat"> 确认行为标注；不是 AI 自动语义评分</label><form id="chat"><div class="form-grid">${select('本轮行为 · 人工结构化测试标注','claim_type',Object.entries(M.BEHAVIORS),'UNREVIEWED')}</div><div class="chat-input"><input name="text" aria-label="销售发言" placeholder="输入本轮销售发言…" required autocomplete="off"><button class="primary" aria-label="发送">${icon('send')}</button></div></form><div class="step-footer"><span>评分将在结束演练后展示</span>${button('结束演练并评分','end-role','secondary')}</div>`);}
case 'VISIT_RECORD':{const rp=x.roleplays.at(-1);return head('08 / VISIT RECORD','3 分钟拜访记录','录入目标约 3 分钟；客户表达、观察和判断分别填写。')+(rp?.score?`<details class="score"><summary>最近演练评分 · Mock AI ${tag(rp.score.every(s=>s.value!==null)?rp.score.reduce((n,s)=>n+s.value,0)+'/10':'N/A')}</summary>${rp.score.map(s=>`<p><b>${s.label}：${s.value??'N/A'}/2</b><br><span>${esc(s.basis)}</span></p>`).join('')}<p>改进：追问具体影响；明确下一步由谁、何时确认。人工结构化测试评分不等于 AI 自动语义评价或销售能力测评。</p></details>`:'')+(x.caseType==='SIMULATED'?button(icon('flask-conical')+'填入独立模拟拜访记录','fill-visit','secondary'):banner('真实案例只接收脱敏真实记录，演练内容不可导入。'))+`<form id="visit"><div class="form-grid">${select('记录性质','caseType',[[x.caseType,x.caseType==='SIMULATED'?'模拟拜访（非演练转录）':'真实脱敏拜访']],x.caseType)}${field('日期','date',M.date(),'date','required')}</div>${field('参与人员（代号与岗位）','participants','','text','required')}${field('本次记录项目代号（未明确可留空）','project_id','')}${area('客户明确表达（转述）','statements')}${area('新需求：客户明确希望改善什么','needs', '',2)}<div class="form-grid">${area('现场观察 / 资料所载（未独立核实）','observations')}${area('新异议：谁提出、针对什么','objections')}</div>${area('下一步：谁、何时、做什么','next','',2)}${select('客户是否明确同意该下一步','agreed',[['unknown','未知 / 未约定'],['yes','明确同意'],['no','未同意']],'unknown')}<div class="form-grid">${area('我的销售判断','judgment')}${area('待验证信息','unknown')}</div><label class="checkbox"><input type="checkbox" required> 确认该记录独立于角色演练，案例性质正确且已脱敏</label><div class="step-footer"><span>提交后仍需信息提取与人工确认</span><button class="primary">提交拜访记录 ${icon('arrow-right')}</button></div></form>`;}
case 'DEBRIEF':{const d=x.debrief;return head('09 / DEBRIEF',`V${x.version} → V${x.draftVersion} 拜访复盘`,'新版尚未保存；新信息必须已完成人工审核。')+`<div class="recap-grid">${[['新增信息',d.newIds],['变化信息',d.changed],['正向需求信号',d.needs],['仍然未知',d.unknown]].map(([t,ids])=>`<div><h3>${t}</h3><p>${refs(ids)||'无'}</p></div>`).join('')}</div><h3>需求假设变化</h3>${d.hypotheses.map(h=>`<div class="understanding">${ref(h.id)}<span>${strength(h.before)} → ${strength(h.after)} ${tag(h.status)}</span></div>`).join('')}<dl><dt>被否定假设</dt><dd>${refs(d.denied)||'无'} · 仅限该假设适用范围</dd><dt>支持与反证并存</dt><dd>${refs(d.mixed)||'无'} · 不自动覆盖旧证据</dd><dt>客户关系</dt><dd>${esc(d.relationship)}</dd><dt>需求变化</dt><dd>表达、理解变化与实际需求变化须分开，冲突保留待核实。</dd><dt>做得好的地方</dt><dd>${esc(d.good)}</dd><dt>存在的问题</dt><dd>${esc(d.problem)}</dd><dt>下次最重要的事</dt><dd>${esc(d.priority)}</dd></dl>`+footer('比较依据：上一版本 + 拜访前假设快照','advance','检查商机证据');}
case 'OPPORTUNITY_CHECK':return head('10 / OPPORTUNITY EVIDENCE CHECK','商机证据检查','每个维度验证证据方向、相关性与范围。信息数量不决定阶段。')+banner('当前为 Mock AI / 模拟实现。未人工确认的语义候选不支持升级；阶段判断只读取结构化有效证据。')+`<div class="table-wrap"><table><thead><tr><th>维度</th><th>状态 / 强度</th><th>证据</th><th>缺口</th></tr></thead><tbody>${x.assessment.map(a=>`<tr><td><strong>${a.label}</strong></td><td>${tag(a.status)}<br>${strength(a.strength)}</td><td>${refs(a.informationIds)} ${ref(a.evidenceId)}${a.oppositionIds?.length?`<div>反对 ${refs(a.oppositionIds)}</div>`:''}</td><td>${esc(a.gap)}</td></tr>`).join('')}</tbody></table></div><div class="stage-band"><span class="stage-number">${x.opportunityStage.stage}</span><div><div class="eyebrow">CURRENT OPPORTUNITY STAGE</div><h3>${M.STAGE_ZH[x.opportunityStage.stage]} <small>${M.STAGES[x.opportunityStage.stage]}</small></h3></div></div><dl><dt>为什么是当前阶段</dt><dd>${esc(x.opportunityStage.why)}</dd><dt>支持证据 / 强度</dt><dd>${refs(x.opportunityStage.supportIds)||'无'} ${strength(x.opportunityStage.strength||'unknown')}</dd><dt>缺失条件</dt><dd>${esc(x.opportunityStage.missingConditions?.join('；')||'见下一阶段核实事项')}</dd><dt>为何不能进入下一阶段</dt><dd>${esc(x.opportunityStage.nextGap)}</dd><dt>最大的证据缺口</dt><dd>${esc(x.opportunityStage.largestGap)}</dd></dl><details><summary>完整机会阶段体系 0—6</summary>${M.STAGES.map((s,n)=>`<p>${n} · ${M.STAGE_ZH[n]} / ${s}</p>`).join('')}</details>`+footer('不生成成交概率或采购承诺','advance','生成行动草稿');
case 'ACTION_REVIEW':return head('11 / ACTION REVIEW','下一步行动，等待你确认','内部接受不代表客户已同意。修改后需要再次接受。')+x.actions.filter(a=>a.round===x.version+1).map(a=>`<article class="action-item"><div class="row between"><span>${ref(a.id)} ${tag(a.status)}</span><div>${ib('pencil','edit-action','修改行动',`data-id="${a.id}"`)}${ib('trash-2','reject-action','不执行行动',`data-id="${a.id}"`)}${button(icon('check')+'接受','accept-action','small',`data-id="${a.id}" ${a.status==='ACCEPTED'||a.status==='REJECTED'?'disabled':''}`)}</div></div><h3>${esc(a.title)}</h3><dl><dt>目的 / 对象</dt><dd>${esc(a.purpose)} · ${esc(a.target)}</dd><dt>建议时间</dt><dd>${esc(a.time)} ${tag(a.timeType)}</dd><dt>依据</dt><dd>${refs(a.basis)||'信息缺口'}</dd><dt>预期结果</dt><dd>${esc(a.expected)}</dd></dl></article>`).join('')+footer('本轮行动全部处理后才可保存','confirm-actions','确认行动审核完成',x.actions.filter(a=>a.round===x.version+1).some(a=>!['ACCEPTED','REJECTED'].includes(a.status)));
case 'VERSION_SAVE':return head('12 / VERSION SAVE',x.saved?`V${x.version} 已保存`:`确认并保存 V${x.draftVersion}`,x.saved?'完整快照已保存到当前浏览器；可导出 JSON 备份。':'保存前检查信息审核、引用有效性和行动确认状态。')+changeSummary(x)+banner('本地存储：已实现。外部联系：未执行。真实 LLM：待实现。')+(x.saved?footer('下次拜访沿用稳定信息编号','next-round','准备下一轮拜访'):footer('完整快照包含来源、证据、假设、行动与变化日志','save-version',`保存 V${x.draftVersion}`));
default:return '';}}
function infoTable(x,items,reviewing=false){return `<div class="table-wrap"><table class="info-table"><thead><tr><th>信息 / 来源</th><th>原始内容与归属审核</th><th>审核</th><th>操作</th></tr></thead><tbody>${items.map(i=>`<tr class="${i.status!=='ACTIVE'?'inactive':''}"><td>${ref(i.id)}<div>${refs(i.sourceIds)}</div><small>${esc(i.time)} · r${i.revision}</small></td><td><small>原始内容</small><p>${esc(i.rawContent??i.content)}</p>${i.rawContent&&i.rawContent!==i.content?`<small>修订内容</small><p>${esc(i.content)}</p>`:''}<div>Mock AI 建议类型：${i.suggestedType?infoTag(i.suggestedType):tag('旧记录未重判')}</div>${i.conflictReason?`<p class="attribution-conflict">冲突原因：${esc(i.conflictReason)}</p>`:''}<div>${i.semanticReviewed?tag('语义已人工确认'):tag('语义待验证：不支持业务升级')}${(i.assertions||[]).map(a=>`<small>${esc(M.TARGETS[a.target])} · ${esc(a.polarity)}</small>`).join('<br>')}</div><div>最终人工确认类型：${i.reviewStatus==='CONFIRMED'?infoTag(i.finalType||i.type):tag('待人工确认')}</div>${i.authorOverride?.reason?`<p>人工归属依据：${esc(i.authorOverride.reason)}</p>`:''}${i.status!=='ACTIVE'?tag(i.status):''}${i.conflicts.length?`<div>冲突 ${refs(i.conflicts)}</div>`:''}${i.replaces.length?`<div>拟取代 ${refs(i.replaces)}</div>`:''}</td><td>${tag(i.reviewStatus==='CONFIRMED'?'已审核':'待审核',i.reviewStatus==='CONFIRMED'?'confirmed':'pending')}</td><td><div class="tools">${reviewing?ib('check','accept-info','接受记录',`data-id="${i.id}" ${i.reviewStatus==='CONFIRMED'?'disabled':''}`)+ib('pencil','edit-info','修改信息',`data-id="${i.id}"`)+ib('circle-help','unknown-info','标记待验证并确认保留',`data-id="${i.id}"`)+ib('trash-2','delete-info','删除有效信息（保留日志）',`data-id="${i.id}"`):ib('file-pen-line','correct-info','启动人工纠错',`data-id="${i.id}"`)}</div></td></tr>`).join('')}</tbody></table></div>`;}
function ledger(x){return head('INFORMATION LEDGER','客户信息台账','已确认信息只能通过显式纠错与重新审核修改。')+(x.information.length?infoTable(x,x.information):'<p class="empty">尚未提取信息</p>');}
function changeSummary(x,snapshot){const old=x.versions.at(-1)?.snapshot;const current=snapshot||x;return `<div class="recap-grid"><div><h3>新增信息</h3><p>${refs(current.information.filter(i=>!old?.information.some(o=>o.id===i.id)).map(i=>i.id))||'无新增'}</p></div><div><h3>删除 / 取代</h3><p>${refs(current.information.filter(i=>['RETRACTED','SUPERSEDED'].includes(i.status)).map(i=>i.id))||'无'}</p></div><div><h3>当前商机阶段</h3><p>${current.opportunityStage?current.opportunityStage.stage+' · '+M.STAGE_ZH[current.opportunityStage.stage]:'未评估'}</p></div><div><h3>待验证信息</h3><p>${refs(current.information.filter(i=>i.type==='UNVERIFIED'&&i.status==='ACTIVE').map(i=>i.id))||'无明确登记'}</p></div></div>`;}
function history(x){return head('VERSION HISTORY','版本历史','确认版本为独立快照。草稿变更不会回写旧版本。')+(x.versions.length?x.versions.slice().reverse().map((v)=>{const prev=x.versions.find(p=>p.number===v.number-1)?.snapshot,s=v.snapshot;const added=s.information.filter(i=>!prev?.information.some(o=>o.id===i.id));const changed=s.information.filter(i=>{const o=prev?.information.find(o=>o.id===i.id);return o&&JSON.stringify(o)!==JSON.stringify(i);});return `<article class="version-item"><div class="row between"><h3>V${v.number} ${tag('已确认','confirmed')}</h3>${ib('download','export-version','导出完整版本',`data-number="${v.number}"`)}</div><p class="muted-text">${new Date(v.at).toLocaleString('zh-CN')}</p><dl><dt>新增</dt><dd>${added.map(i=>esc(i.id)).join('、')||'无'}</dd><dt>修改 / 删除 / 取代</dt><dd>${changed.map(i=>`${esc(i.id)} · ${esc(i.status)}`).join('；')||'无'}</dd><dt>机会阶段</dt><dd>${prev?.opportunityStage?.stage??'未评估'} → ${s.opportunityStage?.stage??'未评估'}</dd><dt>假设 / 等级</dt><dd>${s.hypotheses.map(h=>`${h.id} ${h.status} · ${prev?.hypotheses.find(o=>o.id===h.id)?.strength||'新增'} → ${h.strength}`).join('；')||'未生成'}</dd><dt>确认行动</dt><dd>${s.actions.filter(a=>a.status==='ACCEPTED').map(a=>esc(a.title)).join('；')||'无'}</dd></dl><details><summary>查看此版本的信息快照与审计记录</summary>${s.information.map(i=>`<p><b>${i.id}</b> ${esc(i.content)} ${infoTag(i.type)} ${tag(i.status)}</p>`).join('')}<h4>Evidence Snapshot</h4><pre class="raw">${esc(JSON.stringify(s.evidence,null,2))}</pre><pre class="raw">${esc(JSON.stringify(s.changeLog,null,2))}</pre></details></article>`;}).join(''):'<p class="empty">完成首次信息审核后建立 V1。</p>');}
function evidencePanel(x){const collections={I:x.information,S:x.sources,E:x.evidence,H:x.hypotheses};const items=collections[evTab];const item=i=>`<article class="evidence-item ${focusId===i.id?'focused':''}" id="ev-${i.id}"><strong>${esc(i.evidence_id||i.id)}</strong><p>${esc(i.content||i.title||i.target)}</p>${evTab==='E'?evidenceDetail(i):evTab==='I'?`${infoTag(i.type)}<p>${esc(i.reviewStatus)} · ${esc(i.status)}</p>${refs(i.sourceIds)}`:evTab==='S'?`${tag('SOURCE')}<p>${esc(i.origin)} · ${esc(i.verification)}</p><p>${esc(i.date)} · ${esc(i.location)}</p><p>${esc(i.scope)}</p>`:`${tag(i.evidenceState||i.status)}<p>${esc(i.verify)}</p>${refs(i.evidenceIds)}`}</article>`;return `<aside class="evidence"><div class="evidence-heading"><h2>Evidence Panel</h2></div><div class="evidence-tabs">${Object.keys(collections).map(k=>button(k+' <small>'+collections[k].length+'</small>','ev-tab',evTab===k?'selected':'',`data-ev="${k}"`)).join('')}</div><div class="evidence-items">${evTab==='E'?`<h3>CURRENT VALID EVIDENCE</h3>${items.filter(e=>e.validity==='VALID').map(item).join('')||'<p>无</p>'}<h3>HISTORICAL / INVALIDATED / UNVERIFIED</h3>${items.filter(e=>e.validity!=='VALID').map(item).join('')||'<p>无</p>'}`:items.map(item).join('')||'<p>暂无记录</p>'}</div><div class="evidence-note">SOURCE 是出处，不是事实等级。</div></aside>`;}
function semanticForm(i){const rows=i.assertions?.length?i.assertions:(i.propositions?.length?i.propositions.map(p=>({target:p.target,polarity:'UNKNOWN'})):[{target:'unknown',polarity:'UNKNOWN'}]);return `<fieldset><legend>结构化命题审核 · 人工确认</legend><p>文本解析仅提供候选。未确认语义不会支持需求或阶段。</p>${rows.map((a,n)=>`<div data-assertion class="understanding"><div class="form-grid">${select('对应命题','target'+n,Object.entries(M.TARGETS),a.target)}${select('对该命题的方向','polarity'+n,M.POLARITIES.map(p=>[p,p]),a.polarity)}</div>${field('项目范围值（scope 命题必填）','scope'+n,a.scopeValue||'')}${field('反证 Evidence IDs（可留空）','contradicts'+n,(a.contradicts||[]).join(','))}${field('明确取代 Evidence IDs（可留空）','supersedes'+n,(a.supersedes||[]).join(','))}</div>`).join('')}<label class="checkbox"><input type="checkbox" name="confirmSemantic"> 我已核对每项命题、方向与原始出处</label></fieldset>`;}
function evidenceDetail(e){if(!e.evidence_id)return '<p>旧版汇总 · 非当前判断依据</p>';return `<dl><dt>Author / Semantic Role</dt><dd>${esc(e.author)} / ${esc(e.semantic_role)}</dd><dt>Source</dt><dd>${refs(e.source)}</dd><dt>命题 / Polarity / Validity</dt><dd>${esc(M.TARGETS[e.target]||e.target)}<br>${esc(e.polarity)} · ${esc(e.validity||'UNVERIFIED')}</dd><dt>Strength / Project</dt><dd>${strength(e.strength)}<br>${esc(e.project_id||'未确认')}</dd><dt>Created At / 记录时间</dt><dd>${esc(e.created_at)}<br>${esc(e.time)}</dd><dt>Contradicts / Supersedes</dt><dd>${refs(e.contradicts)||'无'} / ${refs(e.supersedes)||'无'}</dd><dt>被反证 / 被取代</dt><dd>${refs(e.invalidated_by)||'无'} / ${refs(e.superseded_by)||'无'}</dd></dl>`;}
function modal(html){$('#modal').innerHTML=html;$('#modal').showModal();window.lucide?.createIcons();}
function close(){ $('#modal').close(); }
function exportFile(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const client=e.target.closest('[data-client]'),reference=e.target.closest('[data-ref]'),b=e.target.closest('[data-action]');if(client){db.selected=client.dataset.client;view='workflow';focusId='';persist();render();return;}if(reference){focusId=reference.dataset.ref;evTab=['I','S','E','H'].includes(focusId[0])?focusId[0]:'I';render();document.getElementById('ev-'+focusId)?.scrollIntoView({block:'nearest',behavior:'smooth'});return;}if(!b)return;
 try{const x=c(),a=b.dataset.action,id=b.dataset.id;if(a==='tab'){view=b.dataset.view;render();return;}if(a==='ev-tab'){evTab=b.dataset.ev;render();return;}if(a==='close'){close();return;}
 if(a==='new'){modal(`<form id="new-client"><div class="modal-head"><h2>新建客户</h2>${ib('x','close','关闭')}</div>${field('客户代号（唯一）','customerId','','text','required')}${field('客户显示名称（脱敏）','name','','text','required')}${select('案例性质','caseType',[['SIMULATED','模拟案例 / Demo Data'],['REAL_DEIDENTIFIED','真实脱敏案例']],'SIMULATED')}<button class="primary">建立客户 ${icon('plus')}</button></form>`);return;}
 if(a==='demo'){const d=M.demoCustomer();let n=2;while(db.customers.some(x=>x.customerId===d.customerId))d.customerId='SIM-ICU-'+String(n++).padStart(3,'0');db.customers.push(d);db.selected=d.customerId;view='workflow';}
 if(a==='capabilities'){modal(`<div class="modal-head"><h2>V1.1 实现状态</h2>${ib('x','close','关闭')}</div><dl><dt>已实现</dt><dd>原始内容与归属审核、类型冲突门槛、证据支持方向与相关性验证、阶段0—6条件检查、演练上下文隔离、不可变版本快照、本地存储。</dd><dt>当前为 Mock AI / 模拟实现</dt><dd>文本候选提取和情境角色回应；需求与阶段只消费人工确认的 Evidence，评分只消费人工结构化行为标注。不是通用语义理解，不发出外部 AI 请求。旧记录须补充语义审核。</dd><dt>待实现</dt><dd>真实LLM、开放域自然语言理解、独立事实核验及经过验证的销售能力评分。复杂或隐含关系仍需人工核实，不能强行升级。</dd></dl>`);return;}
 if(a==='manual-assessment'){modal(`<form id="assessment"><div class="modal-head"><h2>人工商机证据复核</h2>${ib('x','close','关闭')}</div>${banner('人工确认的是证据对阶段的支持，不会修改客户事实。3：具体意向、范围、参与者与内部动作；4：程序已启动；5：与项目关联的方案/商务；6：可核验结果。')}<div class="assessment-rows">${x.assessment.map((r,n)=>`<fieldset><legend>${r.label}</legend><div class="form-grid">${select('状态','status'+n,['有支持','明确否定','未知','冲突'].map(v=>[v,v]),r.status)}${select('证据强度','strength'+n,M.STRENGTHS.map(v=>[v,v]),r.strength)}</div>${field('引用已审核 I 编号（逗号分隔）','refs'+n,r.informationIds.join(','))}${field('评级依据 / 缺口','gap'+n,r.gap)}</fieldset>`).join('')}</div>${select('当前阶段','stage',M.STAGES.map((s,n)=>[String(n),n+' '+M.STAGE_ZH[n]+' / '+s]),String(x.opportunityStage.stage))}${select('阶段6结局','outcome',[['未结局','未结局'],['成交','成交'],['失单','失单']],x.opportunityStage.outcome)}${area('为什么是该阶段（须包含具体范围/项目动作或结果依据）','why',x.opportunityStage.why)}${area('为何不能进入下一阶段 / 阶段6写不适用','nextGap',x.opportunityStage.nextGap)}<label class="checkbox"><input type="checkbox" required> 我已逐项核对引用内容和阶段门槛，不以态度或一般询价判断</label><button class="primary">确认人工复核</button></form>`);return;}
 if(a==='extract')M.extract(x);if(a==='confirm-batch')M.confirmBatch(x);if(a==='advance')M.advance(x);
 if(['accept-info','unknown-info','delete-info'].includes(a))M.review(x,id,{'accept-info':'accept','unknown-info':'unknown','delete-info':'delete'}[a]);
 if(a==='edit-info'){const i=x.information.find(i=>i.id===id);modal(`<form id="edit-info" data-id="${id}"><div class="modal-head"><h2>修改 ${id}</h2>${ib('x','close','关闭')}</div><p>原始内容：${esc(i.rawContent??i.content)}</p>${area('修订内容','content',i.content)}${select('最终拟确认类型','type',M.TYPES.map(t=>[t,t]),i.type)}${area('人工备注（不能代替客户原始出处）','authorReason',i.authorOverride?.reason||'',2)}${field('原句表达者（仅补充未署名原句时填写）','speaker',i.authorConfirmation?.speaker||'')}<label class="checkbox"><input type="checkbox" name="confirmSpeaker"> 我已核对原始出处，确认未改写的原句由上述客户表达；这不是销售判断或备注</label>${semanticForm(i)}${field('冲突信息 IDs（逗号分隔）','conflicts',i.conflicts.join(','))}${field('明确取代的旧信息 IDs（逗号分隔）','replaces',i.replaces.join(','))}${banner('修改留审计记录，不直接确认。修改 FACT 内容需降为待验证；未知归属不能静默升级。')}<button class="primary">保存修改，重新审核</button></form>`);return;}
 if(a==='correct-info'){M.correct(x,id);view='workflow';}
 if(a==='skip-role')M.endRoleplay(x,true);if(a==='end-role')M.endRoleplay(x);
 if(a==='fill-visit'){for(const [k,v] of Object.entries(M.demoVisit)){const el=$('#visit').elements.namedItem(k);if(el)el.value=v;}toast('已填入独立模拟记录，仍需检查并提交');return;}
 if(['accept-action','reject-action'].includes(a))M.reviewAction(x,id,a==='accept-action'?'accept':'reject');
 if(a==='edit-action'){const row=x.actions.find(a=>a.id===id);modal(`<form id="edit-action" data-id="${id}"><div class="modal-head"><h2>修改行动 ${id}</h2>${ib('x','close','关闭')}</div>${field('下一步行动','title',row.title,'text','required')}${field('目的','purpose',row.purpose)}${field('对象','target',row.target)}${field('建议时间','time',row.time)}${field('预期结果','expected',row.expected)}${banner('修改时间仍为销售内部计划，不代表客户已同意。')}<button class="primary">保存修订，等待接受</button></form>`);return;}
 if(a==='confirm-actions')M.confirmActions(x);if(a==='save-version'){M.saveVersion(x);toast('已保存 V'+x.version+' 完整本地快照');}if(a==='next-round')M.nextRound(x);
 if(a==='export'){if(!x)throw Error('没有当前客户');exportFile({format:'MedSalesBackupV1',customer:x},x.customerId+'.json');return;}
 if(a==='export-version'){const v=x.versions.find(v=>v.number===Number(b.dataset.number));exportFile(v,`${x.customerId}-V${v.number}.json`);return;}
 if(a==='import'){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const data=JSON.parse(await input.files[0].text());if(data.format!=='MedSalesBackupV1'||!data.customer)throw Error('请选择客户完整备份（不是单版本导出）');const n=data.customer; if(!n.customerId||!M.STATES.includes(n.state)||!['SIMULATED','REAL_DEIDENTIFIED'].includes(n.caseType)||!Array.isArray(n.versions)||!Array.isArray(n.information)||!Array.isArray(n.sources))throw Error('备份结构不完整');if(db.customers.some(x=>x.customerId===n.customerId))throw Error('已有同代号客户。为避免覆盖，未导入。');for(const i of n.information)if(!M.TYPES.includes(i.type)||!i.sourceIds.every(r=>n.sources.some(s=>s.id===r)))throw Error('备份引用或标签无效');db.customers.push(n);db.selected=n.customerId;persist();render();toast('客户备份已导入');}catch(err){toast(err.message);}};input.click();return;}
 persist();render();if(['advance','confirm-batch','extract'].includes(a))window.scrollTo(0,0);
 }catch(err){toast(err.message);}});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target;if(busy)return;busy=true;try{const x=c(),v=values(f);switch(f.id){case 'new-client':if(db.customers.some(x=>x.customerId===v.customerId.trim()))throw Error('客户代号已存在');const n=M.createCustomer(v);db.customers.push(n);db.selected=n.customerId;view='workflow';close();break;case 'intake':M.stageInput(x,v);break;case 'edit-info':M.review(x,f.dataset.id,'edit',{...v,assertions:Array.from(f.querySelectorAll('[data-assertion]')).map((row,n)=>({target:v['target'+n],polarity:v['polarity'+n],scopeValue:v['scope'+n],contradicts:(v['contradicts'+n]||'').split(/[,，\s]+/).filter(Boolean),supersedes:(v['supersedes'+n]||'').split(/[,，\s]+/).filter(Boolean)})),conflicts:v.conflicts.split(/[,，\s]+/).filter(Boolean),replaces:v.replaces.split(/[,，\s]+/).filter(Boolean)});close();break;case 'plan':M.confirmPlan(x,{...v,questions:v.questions.split('\n').filter(Boolean)});break;case 'roleplay-start':M.startRoleplay(x,v.role,v.style);break;case 'chat':M.chat(x,v.text,{claim_type:v.claim_type,reviewed:!!v.behaviorReviewed});break;case 'visit':M.recordVisit(x,v);break;case 'edit-action':M.reviewAction(x,f.dataset.id,'edit',{...v,timeType:'销售自定'});close();break;}persist();render();if(f.id==='chat'){const el=$('#chat-log');if(el)el.scrollTop=el.scrollHeight;$('#chat input')?.focus();}}catch(err){toast(err.message);}finally{busy=false;}});
document.addEventListener('submit',e=>{if(e.target.id!=='assessment')return;e.preventDefault();e.stopImmediatePropagation();try{const v=values(e.target),rows=M.DIMENSIONS.map((label,n)=>({label,status:v['status'+n],strength:v['strength'+n],informationIds:v['refs'+n].split(/[,，\s]+/).filter(Boolean),gap:v['gap'+n]}));M.manualAssessment(c(),rows,Number(v.stage),v.why,v.nextGap,v.outcome);persist();close();render();toast('人工复核已记录；客户信息未被修改');}catch(err){toast(err.message);}},true);
document.addEventListener('input',e=>{if(e.target.id==='search'){const p=e.target.selectionStart;filter=e.target.value;render();$('#search')?.focus();$('#search')?.setSelectionRange(p,p);}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))close();});
render();
const _render=render;
render=function(){
 _render();const x=c(),t=document.querySelector('.workspace-title');if(!x||!t)return;
 const s=customerSummary(x),h=document.createElement('section');h.className='customer-hero';
 h.innerHTML=`<div><span class="hero-eyebrow">CUSTOMER INTELLIGENCE · ${esc(s.caseLabel)}</span><h2>${esc(x.name)}</h2><p>${esc(x.intake.department||'科室未知')} · ${esc(s.project)}</p><div class="hero-metrics"><span><b>${s.stage===null?'—':String(s.stage).padStart(2,'0')}</b><small>${s.stage===null?'尚未评估':esc(M.STAGE_ZH[s.stage])}</small></span><span><b>${s.evidenceCount}</b><small>当前客户有效证据</small></span><span><b>${s.openCount}</b><small>待核实信息</small></span></div></div><div class="hero-ai"><span>AI COPILOT · Mock AI</span><strong>${esc(s.insight)}</strong><small>下一步草稿：${esc(s.next)}</small></div>`;
 t.replaceWith(h);document.querySelector('.flow-strip')?.remove();document.querySelector('.evidence')?.classList.add('intelligence-drawer');
};
render();persist();
